import type { QueryInterface } from 'sequelize';
import type { Course } from '@packages/shared-types';
import { v4 as uuidv4 } from 'uuid';

export default {
  up: async (queryInterface: QueryInterface) => {
    const csDept = await queryInterface.sequelize.query(
      "SELECT id FROM departments WHERE code='CS' LIMIT 1"
    );
    const teacher = await queryInterface.sequelize.query(
      "SELECT id FROM users WHERE role='SUPER_ADMIN' LIMIT 1"
    );
    const deptId = (csDept as any)[0][0]?.id;
    const teacherId = (teacher as any)[0][0]?.id;
    if (!deptId || !teacherId) return;
    const now = new Date();
    const courses = [
      {
        id: uuidv4(),
        course_code: 'CS101',
        course_number: '101',
        name: '计算机科学导论',
        english_name: 'Introduction to Computer Science',
        credit: 3.0,
        credit_hours: 48,
        course_type: 'COMPULSORY',
        department_id: deptId,
        teacher_id: teacherId,
        academic_year: '2024-2025',
        semester: 'FALL',
        capacity: 100,
        min_quota: 10,
        enrolled_count: 0,
        status: 'PUBLISHED',
        schedule: { weekly: [], specific_dates: [] },
        location_type: 'CLASSROOM',
        location_details: {},
        description: null,
        objectives: null,
        syllabus: null,
        assessment_method: null,
        textbook_reference: null,
        attachments: [],
        restrictions: {
          grade_limits: [],
          major_limits: [],
          prerequisites: [],
          conflict_courses: [],
        },
        view_count: 0,
        favorite_count: 0,
        review_notes: null,
        reviewed_at: now,
        reviewed_by: teacherId,
        published_at: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: uuidv4(),
        course_code: 'CS201',
        course_number: '201',
        name: '数据结构与算法',
        english_name: 'Data Structures and Algorithms',
        credit: 4.0,
        credit_hours: 64,
        course_type: 'COMPULSORY',
        department_id: deptId,
        teacher_id: teacherId,
        academic_year: '2024-2025',
        semester: 'FALL',
        capacity: 80,
        min_quota: 15,
        enrolled_count: 0,
        status: 'PUBLISHED',
        schedule: { weekly: [], specific_dates: [] },
        location_type: 'CLASSROOM',
        location_details: {},
        description: null,
        objectives: null,
        syllabus: null,
        assessment_method: null,
        textbook_reference: null,
        attachments: [],
        restrictions: {
          grade_limits: [],
          major_limits: [],
          prerequisites: ['CS101'],
          conflict_courses: [],
        },
        view_count: 0,
        favorite_count: 0,
        review_notes: null,
        reviewed_at: now,
        reviewed_by: teacherId,
        published_at: now,
        created_at: now,
        updated_at: now,
      },
      {
        id: uuidv4(),
        course_code: 'CS301',
        course_number: '301',
        name: '数据库系统原理',
        english_name: 'Database System Principles',
        credit: 3.0,
        credit_hours: 48,
        course_type: 'COMPULSORY',
        department_id: deptId,
        teacher_id: teacherId,
        academic_year: '2024-2025',
        semester: 'FALL',
        capacity: 60,
        min_quota: 10,
        enrolled_count: 0,
        status: 'PUBLISHED',
        schedule: { weekly: [], specific_dates: [] },
        location_type: 'CLASSROOM',
        location_details: {},
        description: null,
        objectives: null,
        syllabus: null,
        assessment_method: null,
        textbook_reference: null,
        attachments: [],
        restrictions: {
          grade_limits: [],
          major_limits: [],
          prerequisites: ['CS201'],
          conflict_courses: [],
        },
        view_count: 0,
        favorite_count: 0,
        review_notes: null,
        reviewed_at: now,
        reviewed_by: teacherId,
        published_at: now,
        created_at: now,
        updated_at: now,
      },
    ];
    const typeCheck = courses.map(x => ({
      id: String(x.id),
      course_code: x.course_code,
      course_number: x.course_number ?? null,
      name: x.name,
      english_name: x.english_name ?? null,
      credit: x.credit,
      credit_hours: x.credit_hours,
      course_type: x.course_type as Course['course_type'],
      department_id: String(x.department_id),
      teacher_id: String(x.teacher_id),
      academic_year: x.academic_year,
      semester: x.semester as Course['semester'],
      capacity: x.capacity,
      min_quota: x.min_quota,
      enrolled_count: x.enrolled_count,
      status: x.status as Course['status'],
      schedule: x.schedule,
      location_type: x.location_type as Course['location_type'],
      location_details: x.location_details as any,
      description: x.description ?? null,
      objectives: x.objectives ?? null,
      syllabus: x.syllabus ?? null,
      assessment_method: x.assessment_method ?? null,
      textbook_reference: x.textbook_reference ?? null,
      attachments: x.attachments as any,
      restrictions: x.restrictions as any,
      view_count: x.view_count,
      favorite_count: x.favorite_count,
      review_notes: x.review_notes ?? null,
      reviewed_at: (x.reviewed_at as Date).toISOString(),
      reviewed_by: String(x.reviewed_by),
      published_at: (x.published_at as Date).toISOString(),
      created_at: (x.created_at as Date).toISOString(),
      updated_at: (x.updated_at as Date).toISOString(),
    })) satisfies Course[];
    for (const c of typeCheck) {
      await queryInterface.sequelize.query(
        `INSERT INTO courses (
          id, course_code, course_number, name, english_name, credit, credit_hours, course_type,
          department_id, teacher_id, academic_year, semester, capacity, min_quota, enrolled_count,
          status, schedule, location_type, location_details, description, objectives, syllabus,
          assessment_method, textbook_reference, attachments, restrictions, view_count, favorite_count,
          review_notes, reviewed_at, reviewed_by, published_at, created_at, updated_at
        ) VALUES (
          :id, :course_code, :course_number, :name, :english_name, :credit, :credit_hours, :course_type,
          :department_id, :teacher_id, :academic_year, :semester, :capacity, :min_quota, :enrolled_count,
          :status, :schedule::jsonb, :location_type, :location_details::jsonb, :description, :objectives, :syllabus,
          :assessment_method, :textbook_reference, :attachments::jsonb, :restrictions::jsonb, :view_count, :favorite_count,
          :review_notes, :reviewed_at, :reviewed_by, :published_at, :created_at, :updated_at
        ) ON CONFLICT (course_code) DO NOTHING`,
        {
          replacements: {
            id: c.id,
            course_code: c.course_code,
            course_number: c.course_number,
            name: c.name,
            english_name: c.english_name,
            credit: c.credit,
            credit_hours: c.credit_hours,
            course_type: c.course_type,
            department_id: c.department_id,
            teacher_id: c.teacher_id,
            academic_year: c.academic_year,
            semester: c.semester,
            capacity: c.capacity,
            min_quota: c.min_quota,
            enrolled_count: c.enrolled_count,
            status: c.status,
            schedule: JSON.stringify(c.schedule),
            location_type: c.location_type,
            location_details: JSON.stringify(c.location_details),
            description: c.description,
            objectives: c.objectives,
            syllabus: c.syllabus,
            assessment_method: c.assessment_method,
            textbook_reference: c.textbook_reference,
            attachments: JSON.stringify(c.attachments),
            restrictions: JSON.stringify(c.restrictions),
            view_count: c.view_count,
            favorite_count: c.favorite_count,
            review_notes: c.review_notes,
            reviewed_at: c.reviewed_at,
            reviewed_by: c.reviewed_by,
            published_at: c.published_at,
            created_at: c.created_at,
            updated_at: c.updated_at,
          },
        }
      );
    }
  },
  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete('courses', { course_code: ['CS101', 'CS201', 'CS301'] });
  },
};
